Index: tests_0-8/basic.py
===================================================================
--- tests_0-8/basic.py	(revision 732436)
+++ tests_0-8/basic.py	(working copy)
@@ -98,7 +98,7 @@
             channel.basic_consume(queue="")
             self.fail("Expected failure when consuming from unspecified queue")
         except Closed, e:
-            self.assertConnectionException(530, e.args[0])
+            self.assertChannelException(404, e.args[0])
 
     def test_consume_unique_consumers(self):
         """
Index: tests_0-8/queue.py
===================================================================
--- tests_0-8/queue.py	(revision 732436)
+++ tests_0-8/queue.py	(working copy)
@@ -38,13 +38,13 @@
         channel.basic_publish(exchange="test-exchange", routing_key="key", content=Content("three"))
 
         #check that the queue now reports 3 messages:
-        reply = channel.queue_declare(queue="test-queue")
+        reply = channel.queue_declare(queue="test-queue", exclusive=True)
         self.assertEqual(3, reply.message_count)
 
         #now do the purge, then test that three messages are purged and the count drops to 0
         reply = channel.queue_purge(queue="test-queue");
         self.assertEqual(3, reply.message_count)        
-        reply = channel.queue_declare(queue="test-queue")
+        reply = channel.queue_declare(queue="test-queue", exclusive=True)
         self.assertEqual(0, reply.message_count)
 
         #send a further message and consume it, ensuring that the other messages are really gone
@@ -71,7 +71,7 @@
             channel.queue_purge()
             self.fail("Expected failure when purging unspecified queue")
         except Closed, e:
-            self.assertConnectionException(530, e.args[0])
+            self.assertChannelException(404, e.args[0])
 
         #cleanup    
         other = self.connect()
